export const dummyData=[
    {
        "id": 1,
        "firstName": "Emily",
        "lastName": "Johnson",
        "email": "emily.johnson@x.dummyjson.com",
        "gender": "female",
        "age": 28,
        "city": "San Francisco",
    },
    {
        "id": 2,
        "firstName": "Emily",
        "lastName": "Johnson",
        "email": "emily.johnson@x.dummyjson.com",
        "gender": "female",
        "age": 28,
        "city": "San Francisco",
    },
    {
        "id": 3,
        "firstName": "Emily",
        "lastName": "Johnson",
        "email": "emily.johnson@x.dummyjson.com",
        "gender": "female",
        "age": 28,
        "city": "San Francisco",
    },{
        "id": 4,
        "firstName": "Emily",
        "lastName": "Johnson",
        "email": "emily.johnson@x.dummyjson.com",
        "gender": "female",
        "age": 28,
        "city": "San Francisco",
    },{
        "id": 5,
        "firstName": "Emily",
        "lastName": "Johnson",
        "email": "emily.johnson@x.dummyjson.com",
        "gender": "female",
        "age": 28,
        "city": "San Francisco",
    },{
        "id": 6,
        "firstName": "Emily",
        "lastName": "Johnson",
        "email": "emily.johnson@x.dummyjson.com",
        "gender": "female",
        "age": 28,
        "city": "San Francisco",
    },{
        "id": 7,
        "firstName": "Emily",
        "lastName": "Johnson",
        "email": "emily.johnson@x.dummyjson.com",
        "gender": "female",
        "age": 28,
        "city": "San Francisco",
    },{
        "id": 8,
        "firstName": "Emily",
        "lastName": "Johnson",
        "email": "emily.johnson@x.dummyjson.com",
        "gender": "female",
        "age": 28,
        "city": "San Francisco",
    },{
        "id": 9,
        "firstName": "Emily",
        "lastName": "Johnson",
        "email": "emily.johnson@x.dummyjson.com",
        "gender": "female",
        "age": 28,
        "city": "San Francisco",
    },{
        "id": 10,
        "firstName": "Emily",
        "lastName": "Johnson",
        "email": "emily.johnson@x.dummyjson.com",
        "gender": "female",
        "age": 28,
        "city": "San Francisco",
    },{
        "id": 11,
        "firstName": "Emily",
        "lastName": "Johnson",
        "email": "emily.johnson@x.dummyjson.com",
        "gender": "female",
        "age": 28,
        "city": "San Francisco",
    },{
        "id": 12,
        "firstName": "Emily",
        "lastName": "Johnson",
        "email": "emily.johnson@x.dummyjson.com",
        "gender": "female",
        "age": 28,
        "city": "San Francisco",
    },{
        "id": 13,
        "firstName": "Emily",
        "lastName": "Johnson",
        "email": "emily.johnson@x.dummyjson.com",
        "gender": "female",
        "age": 28,
        "city": "San Francisco",
    },{
        "id": 14,
        "firstName": "Emily",
        "lastName": "Johnson",
        "email": "emily.johnson@x.dummyjson.com",
        "gender": "female",
        "age": 28,
        "city": "San Francisco",
    },{
        "id": 15,
        "firstName": "Emily",
        "lastName": "Johnson",
        "email": "emily.johnson@x.dummyjson.com",
        "gender": "female",
        "age": 28,
        "city": "San Francisco",
    },
]